name: Fuzz Test with DeepState

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fuzzing:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libgtest-dev cmake build-essential
          git clone https://github.com/trailofbits/deepstate.git
          cd deepstate
          cmake -DCMAKE_INSTALL_PREFIX=/usr .
          make -j$(nproc)
          sudo make install

      # Step 3: Compile the fuzzer
      - name: Compile Fuzzer
        run: |
          clang++ -g -std=c++17 -ldeepstate validatePayload_fuzzer.cpp -o validatePayload_fuzzer

      # Step 4: Run the fuzzer
      - name: Run Fuzzer
        run: |
          ./validatePayload_fuzzer --fuzz --timeout=60 --output_test_dir=fuzz_results

      # Step 5: Archive results
      - name: Archive Fuzzing Results
        run: |
          tar -czf fuzzing_results.tar.gz fuzz_results
          echo "Fuzzing results archived."

      # Step 6: Upload results
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: fuzzing-results
          path: fuzzing_results.tar.gz
