name: AFL++ CI

on:
  push:
    branches:
      - stable
      - dev
  pull_request:
    branches:
      - dev

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      AFL_SKIP_CPUFREQ: 1
      AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
    steps:
      - uses: actions/checkout@v3
      
      - name: Update System
        run: sudo apt-get update && sudo apt-get upgrade -y
      
      - name: Install Required Packages
        run: |
          sudo apt-get install -y build-essential gcc-10 g++-10 git libtool \
          libtool-bin automake flex bison clang-12 llvm-12-dev \
          libunwind-dev libc++-dev findutils libcmocka-dev python3-dev \
          python3-setuptools ninja-build python3-pip gcc-10-plugin-dev

      - name: Verify Compiler Installation
        run: |
          gcc -v
          clang -v

      - name: Build AFL++
        run: |
          export NO_NYX=1
          export ASAN_BUILD=1
          export LLVM_CONFIG=llvm-config-12
          make ASAN_BUILD=1 NO_NYX=1 LLVM_CONFIG=llvm-config-12 distrib

      - name: Run AFL++ Tests
        run: sudo -E ./afl-system-config && make tests

  macos:
    runs-on: macOS-latest
    env:
      AFL_MAP_SIZE: 65536
      AFL_SKIP_CPUFREQ: 1
      AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Homebrew and Required Tools
        run: |
          brew install make gcc llvm libunwind
      
      - name: Build AFL++ on macOS
        run: |
          export CC=$(brew --prefix llvm)/bin/clang
          export CXX=$(brew --prefix llvm)/bin/clang++
          export LLVM_CONFIG=$(brew --prefix llvm)/bin/llvm-config
          sudo -E ./afl-system-config
          make ASAN_BUILD=1 afl-fuzz

      - name: Run AFL++ Tests on macOS
        run: |
          export CC=$(brew --prefix llvm)/bin/clang
          export CXX=$(brew --prefix llvm)/bin/clang++
          export LLVM_CONFIG=$(brew --prefix llvm)/bin/llvm-config
          make tests
