name: Run Fuzzing and Symbolic Execution Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fuzzing:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install required dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm klee afl++

      # Step 3: Build and run fuzzing with AFL++
      - name: Compile and run AFL++
        run: |
          clang++ -g -O1 -fsanitize=address,fuzzer -o validate_fuzz validate_fuzz.cpp
          mkdir -p afl_input
          echo "test_payload" > afl_input/testcase
          afl-fuzz -i afl_input -o afl_output ./validate_fuzz --timeout=60

      # Step 4: Prepare and run symbolic execution with KLEE
      - name: Run KLEE
        run: |
          clang -I/usr/lib/klee/include -emit-llvm -c -g validate_fuzz.cpp -o validate_fuzz.bc
          klee validate_fuzz.bc

      # Step 5: Generate and display test results
      - name: Upload Results
        run: |
          echo "Uploading results"
          tar -czf results.tar.gz afl_output klee-last
          echo "Results generated"
