name: Fuzzing and Symbolic Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fuzzing:
    runs-on: ubuntu-latest

    steps:
      # Set up Node.js 20 to avoid deprecated version warning
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies (clang, llvm, cmake, etc.)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm cmake make
          sudo apt-get install -y python3 python3-pip
          pip3 install deepstate  # Install DeepState for fuzzing

      # Compile and run DeepState fuzzing (assuming your harness is in fuzzing.cpp)
      - name: Compile and run DeepState fuzzing
        run: |
          clang++ -g -O1 -std=c++17 -I$HOME/deepstate/include fuzzing.cpp -o fuzzing
          ./fuzzing

      # Install KLEE (or another symbolic execution tool)
      - name: Install KLEE
        run: |
          sudo apt-get install -y klee
          klee fuzzing.bc

      # Optionally, upload artifacts or results from fuzzing or symbolic execution
      - name: Upload fuzzing results
        uses: actions/upload-artifact@v3
        with:
          name: fuzzing-results
          path: ./fuzzing_output
