name: Run DeepState Fuzzing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fuzzing:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to use Node.js 20

      # Install dependencies
      - name: Install DeepState and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm cmake make
          sudo apt-get install -y python3 python3-pip
          pip3 install deepstate

      # Compile the DeepState harness
      - name: Compile the Fuzzing Harness
        run: |
          mkdir -p build
          clang++ -g -O1 -std=c++17 -I/usr/local/include/deepstate fuzz/ValidatePayload_fuzzer.cpp -o build/fuzzing

      # Run the fuzzing test
      - name: Run Fuzzing
        run: |
          ./build/fuzzing --fuzz --timeout=30
